name: Bareeq_Store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.1.3
  firebase_auth: ^5.1.3
  url_launcher: ^6.3.0
  provider: ^6.1.2
  go_router: ^14.2.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  file_picker: ^6.1.1
  image_compression_flutter: ^1.0.4
  csv: ^5.0.2
  flutter_stripe: ^9.0.0
  pdf: ^3.11.0
  printing: ^5.11.0
  path_provider: ^2.0.14  
  bidi: ^2.0.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
